-- Seed 52 curated props (hero image each). image_url -> public/images/props/<slug>.jpg
insert into props (name, category, image_url, is_active, sort_order) values
  ('Adjustable Gym Bench','Bench','/images/props/adjustable-gym-bench.jpg',true,10),
  ('Carlos Castaneira Bench','Bench','/images/props/carlos-castaneira-bench.jpg',true,20),
  ('Leather Brown Bench','Bench','/images/props/leather-brown-bench.jpg',true,30),
  ('Leather Brown Metal Bench','Bench','/images/props/leather-brown-metal-bench.jpg',true,40),
  ('Stripe Vintage Bench','Bench','/images/props/stripe-vintage-bench.jpg',true,50),
  ('Adjustable Black Stool','Chairs','/images/props/adjustable-black-stool.jpg',true,10),
  ('Black Salon Chair','Chairs','/images/props/black-salon-chair.jpg',true,20),
  ('Blue School Chair','Chairs','/images/props/blue-school-chair.jpg',true,30),
  ('Brown Leather Boss Chair','Chairs','/images/props/brown-leather-boss-chair.jpg',true,40),
  ('China Red Wicker','Chairs','/images/props/china-red-wicker.jpg',true,50),
  ('Double Papasan','Chairs','/images/props/double-papasan.jpg',true,60),
  ('Gray Rocker Armchair','Chairs','/images/props/gray-rocker-armchair.jpg',true,70),
  ('Green Roller','Chairs','/images/props/green-roller.jpg',true,80),
  ('Metal Folding Chairs','Chairs','/images/props/metal-folding-chairs.jpg',true,90),
  ('Modern Curve Rocker','Chairs','/images/props/modern-curve-rocker.jpg',true,100),
  ('Mustard Vintage Armchair','Chairs','/images/props/mustard-vintage-armchair.jpg',true,110),
  ('Old Warehouse Chair','Chairs','/images/props/old-warehouse-chair.jpg',true,120),
  ('Peacock Chair','Chairs','/images/props/peacock-chair.jpg',true,130),
  ('Purple Vintage Recliner','Chairs','/images/props/purple-vintage-recliner.jpg',true,140),
  ('Rattan Patio Chairs','Chairs','/images/props/rattan-patio-chairs.jpg',true,150),
  ('Rattan Rocker','Chairs','/images/props/rattan-rocker.jpg',true,160),
  ('Red Relaxer','Chairs','/images/props/red-relaxer.jpg',true,170),
  ('Red Side Chair','Chairs','/images/props/red-side-chair.jpg',true,180),
  ('Rolling Blue Executive','Chairs','/images/props/rolling-blue-executive.jpg',true,190),
  ('Soft Blue','Chairs','/images/props/soft-blue.jpg',true,200),
  ('Steel & Brown Leather','Chairs','/images/props/steel-and-brown-leather.jpg',true,210),
  ('Various Stools','Chairs','/images/props/various-stools.jpg',true,220),
  ('Victorian Beige','Chairs','/images/props/victorian-beige.jpg',true,230),
  ('Victorian Tan Highchair','Chairs','/images/props/victorian-tan-highchair.jpg',true,240),
  ('Vintage Blue & Wood','Chairs','/images/props/vintage-blue-and-wood.jpg',true,250),
  ('Vintage Green','Chairs','/images/props/vintage-green.jpg',true,260),
  ('Vintage Rocker','Chairs','/images/props/vintage-rocker.jpg',true,270),
  ('Vintage Wheelchair','Chairs','/images/props/vintage-wheelchair.jpg',true,280),
  ('Wicker High Chair','Chairs','/images/props/wicker-high-chair.jpg',true,290),
  ('Gray Leather Loveseat','Sofas','/images/props/gray-leather-loveseat.jpg',true,10),
  ('Lazyboy Brown Leather Love Couch','Sofas','/images/props/lazyboy-brown-leather-love-couch.jpg',true,20),
  ('Modern Leather Couch','Sofas','/images/props/modern-leather-couch.jpg',true,30),
  ('Red Tassel Ottoman','Sofas','/images/props/red-tassel-ottoman.jpg',true,40),
  ('Teal Vintage Futon','Sofas','/images/props/teal-vintage-futon.jpg',true,50),
  ('Victorian Couch','Sofas','/images/props/victorian-couch.jpg',true,60),
  ('Kitchen Prep Table','Tables','/images/props/kitchen-prep-table.jpg',true,10),
  ('Mid-Century Desk','Tables','/images/props/mid-century-desk.jpg',true,20),
  ('Mid-Century Duo Table','Tables','/images/props/mid-century-duo-table.jpg',true,30),
  ('Mid-Century Side Table','Tables','/images/props/mid-century-side-table.jpg',true,40),
  ('Rough Console Farm Table','Tables','/images/props/rough-console-farrm-table.jpg',true,50),
  ('Wood Farm Side Table','Tables','/images/props/wood-farm-side-table.jpg',true,60),
  ('Step Box','Fitness','/images/props/step-box.jpg',true,10),
  ('Vintage Elliptical','Fitness','/images/props/vintage-eliptical.jpg',true,20),
  ('Neon Skateboard','Misc','/images/props/neon-skateboard.jpg',true,10),
  ('Vintage Bicycle','Misc','/images/props/vintage-bicycle.jpg',true,20),
  ('White Cube','Misc','/images/props/white-cube.jpg',true,30),
  ('Wooden Sleigh','Misc','/images/props/wooden-sleigh.jpg',true,40);
