-- Seed 134 Pending props (provisional names, hidden). is_active=false until reviewed.
insert into props (name, category, image_url, is_active, sort_order) values
  ('Black Adjustable Stool','Chairs','/images/props/black-adjustable-stool.jpg',false,1010),
  ('Plaid Folding Lounge Chair','Chairs','/images/props/plaid-folding-lounge-chair.jpg',false,1020),
  ('Live-Edge Wood Slab Table','Tables','/images/props/live-edge-wood-slab-table.jpg',false,1010),
  ('Treadle Sewing Machine Table 1','Tables','/images/props/treadle-sewing-machine-table-1.jpg',false,1020),
  ('Treadle Sewing Machine Table 2','Tables','/images/props/treadle-sewing-machine-table-2.jpg',false,1030),
  ('White Nightstand 1','Tables','/images/props/white-nightstand-1.jpg',false,1040),
  ('White Nightstand 2','Tables','/images/props/white-nightstand-2.jpg',false,1050),
  ('Gymnastics Props Cart','Fitness','/images/props/gymnastics-props-cart.jpg',false,1010),
  ('Weight Plate Tree','Fitness','/images/props/weight-plate-tree.jpg',false,1020),
  ('Abstract Wood Wall Clock','Misc','/images/props/abstract-wood-wall-clock.jpg',false,1010),
  ('Aluminum Stacked Cases','Misc','/images/props/aluminum-stacked-cases.jpg',false,1020),
  ('Antique Revolver Pistol','Misc','/images/props/antique-revolver-pistol.jpg',false,1030),
  ('Banjo Wall Clock Barometer','Misc','/images/props/banjo-wall-clock-barometer.jpg',false,1040),
  ('Beaded Macrame Skull','Misc','/images/props/beaded-macrame-skull.jpg',false,1050),
  ('Bentwood Round Hat Box','Misc','/images/props/bentwood-round-hat-box.jpg',false,1060),
  ('Black Gun Safe','Misc','/images/props/black-gun-safe.jpg',false,1070),
  ('Black Rotary Telephone 1','Misc','/images/props/black-rotary-telephone-1.jpg',false,1080),
  ('Black Rotary Telephone 2','Misc','/images/props/black-rotary-telephone-2.jpg',false,1090),
  ('Brass Cheval Floor Mirror','Misc','/images/props/brass-cheval-floor-mirror.jpg',false,1100),
  ('Brass Lighted Vanity Mirror','Misc','/images/props/brass-lighted-vanity-mirror.jpg',false,1110),
  ('Brown Leather Duffel','Misc','/images/props/brown-leather-duffel.jpg',false,1120),
  ('Brown Leather Suitcase 4','Misc','/images/props/brown-leather-suitcase-4.jpg',false,1130),
  ('Carved Wood Frame Mirror','Misc','/images/props/carved-wood-frame-mirror.jpg',false,1140),
  ('Chrome Floor Lamp Coat Rack','Misc','/images/props/chrome-floor-lamp-coat-rack.jpg',false,1150),
  ('Clawfoot Bathtub','Misc','/images/props/clawfoot-bathtub.jpg',false,1160),
  ('Dark Leather Suitcase 5','Misc','/images/props/dark-leather-suitcase-5.jpg',false,1170),
  ('Decorative Feather','Misc','/images/props/decorative-feather.jpg',false,1180),
  ('Doctors Balance Scale','Misc','/images/props/doctors-balance-scale.jpg',false,1190),
  ('Dress Form Mannequin','Misc','/images/props/dress-form-mannequin.jpg',false,1200),
  ('Faux Branches In Basket','Misc','/images/props/faux-branches-in-basket.jpg',false,1210),
  ('Faux Broadleaf Plant','Misc','/images/props/faux-broadleaf-plant.jpg',false,1220),
  ('Faux Bushy Plant','Misc','/images/props/faux-bushy-plant.jpg',false,1230),
  ('Faux Fern In Basket','Misc','/images/props/faux-fern-in-basket.jpg',false,1240),
  ('Faux Fiddle-Leaf Plant','Misc','/images/props/faux-fiddle-leaf-plant.jpg',false,1250),
  ('Faux Grass Plant','Misc','/images/props/faux-grass-plant.jpg',false,1260),
  ('Faux Greenery Planter Boxes','Misc','/images/props/faux-greenery-planter-boxes.jpg',false,1270),
  ('Faux Monstera Plant','Misc','/images/props/faux-monstera-plant.jpg',false,1280),
  ('Faux Palm 1','Misc','/images/props/faux-palm-1.jpg',false,1290),
  ('Faux Palm 2','Misc','/images/props/faux-palm-2.jpg',false,1300),
  ('Faux Palm 3','Misc','/images/props/faux-palm-3.jpg',false,1310),
  ('Faux Plant A','Misc','/images/props/faux-plant-a.jpg',false,1320),
  ('Faux Plant B','Misc','/images/props/faux-plant-b.jpg',false,1330),
  ('Faux Plant C','Misc','/images/props/faux-plant-c.jpg',false,1340),
  ('Faux Slim Plant','Misc','/images/props/faux-slim-plant.jpg',false,1350),
  ('Faux Tall Tree','Misc','/images/props/faux-tall-tree.jpg',false,1360),
  ('Faux Willow Plant','Misc','/images/props/faux-willow-plant.jpg',false,1370),
  ('Floor Lamp With Tray Table','Misc','/images/props/floor-lamp-with-tray-table.jpg',false,1380),
  ('Folding Chrome Mirror','Misc','/images/props/folding-chrome-mirror.jpg',false,1390),
  ('Galvanized Metal Toolbox','Misc','/images/props/galvanized-metal-toolbox.jpg',false,1400),
  ('Glass Demijohn Pair','Misc','/images/props/glass-demijohn-pair.jpg',false,1410),
  ('Gold Oriental Fan (Red)','Misc','/images/props/gold-oriental-fan-red.jpg',false,1420),
  ('Gold Oval Wall Mirror','Misc','/images/props/gold-oval-wall-mirror.jpg',false,1430),
  ('Gold Peacock Folding Fan','Misc','/images/props/gold-peacock-folding-fan.jpg',false,1440),
  ('Gold Rococo Wall Mirror','Misc','/images/props/gold-rococo-wall-mirror.jpg',false,1450),
  ('Gray Concrete Cube Planter','Misc','/images/props/gray-concrete-cube-planter.jpg',false,1460),
  ('Gray Cube Planter On Legs','Misc','/images/props/gray-cube-planter-on-legs.jpg',false,1470),
  ('Gray Ottoman Cubes (Set)','Misc','/images/props/gray-ottoman-cubes-set.jpg',false,1480),
  ('Green Military Footlocker','Misc','/images/props/green-military-footlocker.jpg',false,1490),
  ('Green Ornate Table Lamp','Misc','/images/props/green-ornate-table-lamp.jpg',false,1500),
  ('Hourglass Sand Timer','Misc','/images/props/hourglass-sand-timer.jpg',false,1510),
  ('Large Leaning Mirror','Misc','/images/props/large-leaning-mirror.jpg',false,1520),
  ('Leather Round Hat Box','Misc','/images/props/leather-round-hat-box.jpg',false,1530),
  ('Leather Suitcase 2','Misc','/images/props/leather-suitcase-2.jpg',false,1540),
  ('Medieval Sword','Misc','/images/props/medieval-sword.jpg',false,1550),
  ('Mirror Corner Panel','Misc','/images/props/mirror-corner-panel.jpg',false,1560),
  ('Neon Open Sign','Misc','/images/props/neon-open-sign.jpg',false,1570),
  ('Oak Wall Crank Telephone 2','Misc','/images/props/oak-wall-crank-telephone-2.jpg',false,1580),
  ('Oriental Art Panel Pair','Misc','/images/props/oriental-art-panel-pair.jpg',false,1590),
  ('Oriental Art Panel Single','Misc','/images/props/oriental-art-panel-single.jpg',false,1600),
  ('Oriental Bird Art Panel','Misc','/images/props/oriental-bird-art-panel.jpg',false,1610),
  ('Overhead Projector','Misc','/images/props/overhead-projector.jpg',false,1620),
  ('Pampas Grass In Brass Vase','Misc','/images/props/pampas-grass-in-brass-vase.jpg',false,1630),
  ('Patina Steer Skull','Misc','/images/props/patina-steer-skull.jpg',false,1640),
  ('Peacock Feather','Misc','/images/props/peacock-feather.jpg',false,1650),
  ('Potted Palms Cluster 2','Misc','/images/props/potted-palms-cluster-2.jpg',false,1660),
  ('Potted Plants Cluster 1','Misc','/images/props/potted-plants-cluster-1.jpg',false,1670),
  ('Rattan Ball Lantern','Misc','/images/props/rattan-ball-lantern.jpg',false,1680),
  ('Rattan Folding Screen','Misc','/images/props/rattan-folding-screen.jpg',false,1690),
  ('Rattan Lantern With Handle','Misc','/images/props/rattan-lantern-with-handle.jpg',false,1700),
  ('Red Coca-Cola Mini Fridge','Misc','/images/props/red-coca-cola-mini-fridge.jpg',false,1710),
  ('Red Glass Vase With Wheat','Misc','/images/props/red-glass-vase-with-wheat.jpg',false,1720),
  ('Red Hurricane Lantern','Misc','/images/props/red-hurricane-lantern.jpg',false,1730),
  ('Rolled Leather Bedroll','Misc','/images/props/rolled-leather-bedroll.jpg',false,1740),
  ('Round Rattan Striped Pouf','Misc','/images/props/round-rattan-striped-pouf.jpg',false,1750),
  ('Round Rattan Wall Mirror','Misc','/images/props/round-rattan-wall-mirror.jpg',false,1760),
  ('Round Woven Storage Box','Misc','/images/props/round-woven-storage-box.jpg',false,1770),
  ('Rustic Timber Pedestal','Misc','/images/props/rustic-timber-pedestal.jpg',false,1780),
  ('Skull Bookend','Misc','/images/props/skull-bookend.jpg',false,1790),
  ('Small Leather Box','Misc','/images/props/small-leather-box.jpg',false,1800),
  ('Small Wood Chest','Misc','/images/props/small-wood-chest.jpg',false,1810),
  ('Spells Prop Spellbook','Misc','/images/props/spells-prop-spellbook.jpg',false,1820),
  ('Stacked Vintage Trunks (Set)','Misc','/images/props/stacked-vintage-trunks-set.jpg',false,1830),
  ('Steer Skull Canvas Art','Misc','/images/props/steer-skull-canvas-art.jpg',false,1840),
  ('Table Lamp With Brown Shade','Misc','/images/props/table-lamp-with-brown-shade.jpg',false,1850),
  ('Tall Chrome Mirror Panel 1','Misc','/images/props/tall-chrome-mirror-panel-1.jpg',false,1860),
  ('Tall Mirror Panel 2','Misc','/images/props/tall-mirror-panel-2.jpg',false,1870),
  ('Tall Wicker Case','Misc','/images/props/tall-wicker-case.jpg',false,1880),
  ('Tan Leather Suitcase 1','Misc','/images/props/tan-leather-suitcase-1.jpg',false,1890),
  ('Tan Leather Suitcase 3','Misc','/images/props/tan-leather-suitcase-3.jpg',false,1900),
  ('Teal Electric Typewriter','Misc','/images/props/teal-electric-typewriter.jpg',false,1910),
  ('Verdigris Metal Pot','Misc','/images/props/verdigris-metal-pot.jpg',false,1920),
  ('Vintage Bellows Camera 2','Misc','/images/props/vintage-bellows-camera-2.jpg',false,1930),
  ('Vintage Boombox','Misc','/images/props/vintage-boombox.jpg',false,1940),
  ('Vintage Box Camera','Misc','/images/props/vintage-box-camera.jpg',false,1950),
  ('Vintage Cathedral Radio','Misc','/images/props/vintage-cathedral-radio.jpg',false,1960),
  ('Vintage Chrome Electric Iron','Misc','/images/props/vintage-chrome-electric-iron.jpg',false,1970),
  ('Vintage Folding Camera 1','Misc','/images/props/vintage-folding-camera-1.jpg',false,1980),
  ('Vintage Platform Scale','Misc','/images/props/vintage-platform-scale.jpg',false,1990),
  ('Vintage Press Camera 3','Misc','/images/props/vintage-press-camera-3.jpg',false,2000),
  ('Wall Crank Telephone 1','Misc','/images/props/wall-crank-telephone-1.jpg',false,2010),
  ('White Angel Wings','Misc','/images/props/white-angel-wings.jpg',false,2020),
  ('White Female Mannequin','Misc','/images/props/white-female-mannequin.jpg',false,2030),
  ('White Medical Privacy Screen','Misc','/images/props/white-medical-privacy-screen.jpg',false,2040),
  ('White Orthopedic Back Brace','Misc','/images/props/white-orthopedic-back-brace.jpg',false,2050),
  ('White Pedestal Plinth','Misc','/images/props/white-pedestal-plinth.jpg',false,2060),
  ('Wicker Basket Ottoman','Misc','/images/props/wicker-basket-ottoman.jpg',false,2070),
  ('Wicker Box','Misc','/images/props/wicker-box.jpg',false,2080),
  ('Wicker Dome Chest 1','Misc','/images/props/wicker-dome-chest-1.jpg',false,2090),
  ('Wicker Dome Chest 2','Misc','/images/props/wicker-dome-chest-2.jpg',false,2100),
  ('Wicker Trunk 1','Misc','/images/props/wicker-trunk-1.jpg',false,2110),
  ('Wicker Trunk 2 (Open)','Misc','/images/props/wicker-trunk-2-open.jpg',false,2120),
  ('Wood Folding Screen 2','Misc','/images/props/wood-folding-screen-2.jpg',false,2130),
  ('Wood Interlocking Puzzle','Misc','/images/props/wood-interlocking-puzzle.jpg',false,2140),
  ('Wood Louvered Folding Screen 1','Misc','/images/props/wood-louvered-folding-screen-1.jpg',false,2150),
  ('Wood Mantel Clock 1','Misc','/images/props/wood-mantel-clock-1.jpg',false,2160),
  ('Wood Mantel Clock 2','Misc','/images/props/wood-mantel-clock-2.jpg',false,2170),
  ('Wood Metronome','Misc','/images/props/wood-metronome.jpg',false,2180),
  ('Wood Tripod Floor Lamp','Misc','/images/props/wood-tripod-floor-lamp.jpg',false,2190),
  ('Wooden Lap Desk','Misc','/images/props/wooden-lap-desk.jpg',false,2200),
  ('Wooden Phonograph Box','Misc','/images/props/wooden-phonograph-box.jpg',false,2210),
  ('World Globe 1','Misc','/images/props/world-globe-1.jpg',false,2220),
  ('World Globe 2','Misc','/images/props/world-globe-2.jpg',false,2230),
  ('Woven Rattan Box','Misc','/images/props/woven-rattan-box.jpg',false,2240),
  ('Woven Seagrass Mat','Misc','/images/props/woven-seagrass-mat.jpg',false,2250);
