-- 024: prop slugs + multi-image galleries
alter table props add column if not exists slug text;
alter table props add column if not exists gallery jsonb default '[]'::jsonb;

update props p set slug = v.slug, gallery = v.gallery::jsonb
from (values
  ('abstract-wood-wall-clock','["/images/props/abstract-wood-wall-clock.jpg"]'),
  ('adjustable-black-stool','["/images/props/adjustable-black-stool.jpg", "/images/props/adjustable-black-stool/2.jpg"]'),
  ('adjustable-gym-bench','["/images/props/adjustable-gym-bench.jpg", "/images/props/adjustable-gym-bench/2.jpg", "/images/props/adjustable-gym-bench/3.jpg", "/images/props/adjustable-gym-bench/4.jpg", "/images/props/adjustable-gym-bench/5.jpg", "/images/props/adjustable-gym-bench/6.jpg", "/images/props/adjustable-gym-bench/7.jpg"]'),
  ('aluminum-stacked-cases','["/images/props/aluminum-stacked-cases.jpg", "/images/props/aluminum-stacked-cases/2.jpg"]'),
  ('antique-revolver-pistol','["/images/props/antique-revolver-pistol.jpg", "/images/props/antique-revolver-pistol/2.jpg"]'),
  ('banjo-wall-clock-barometer','["/images/props/banjo-wall-clock-barometer.jpg"]'),
  ('beaded-macrame-skull','["/images/props/beaded-macrame-skull.jpg"]'),
  ('bentwood-round-hat-box','["/images/props/bentwood-round-hat-box.jpg"]'),
  ('black-adjustable-stool','["/images/props/black-adjustable-stool.jpg"]'),
  ('black-gun-safe','["/images/props/black-gun-safe.jpg", "/images/props/black-gun-safe/2.jpg"]'),
  ('black-rotary-telephone-1','["/images/props/black-rotary-telephone-1.jpg", "/images/props/black-rotary-telephone-1/2.jpg"]'),
  ('black-rotary-telephone-2','["/images/props/black-rotary-telephone-2.jpg", "/images/props/black-rotary-telephone-2/2.jpg", "/images/props/black-rotary-telephone-2/3.jpg"]'),
  ('black-salon-chair','["/images/props/black-salon-chair.jpg", "/images/props/black-salon-chair/2.jpg", "/images/props/black-salon-chair/3.jpg", "/images/props/black-salon-chair/4.jpg", "/images/props/black-salon-chair/5.jpg"]'),
  ('blue-school-chair','["/images/props/blue-school-chair.jpg", "/images/props/blue-school-chair/2.jpg", "/images/props/blue-school-chair/3.jpg", "/images/props/blue-school-chair/4.jpg"]'),
  ('brass-cheval-floor-mirror','["/images/props/brass-cheval-floor-mirror.jpg", "/images/props/brass-cheval-floor-mirror/2.jpg", "/images/props/brass-cheval-floor-mirror/3.jpg"]'),
  ('brass-lighted-vanity-mirror','["/images/props/brass-lighted-vanity-mirror.jpg", "/images/props/brass-lighted-vanity-mirror/2.jpg", "/images/props/brass-lighted-vanity-mirror/3.jpg", "/images/props/brass-lighted-vanity-mirror/4.jpg"]'),
  ('brown-leather-boss-chair','["/images/props/brown-leather-boss-chair.jpg", "/images/props/brown-leather-boss-chair/2.jpg", "/images/props/brown-leather-boss-chair/3.jpg", "/images/props/brown-leather-boss-chair/4.jpg"]'),
  ('brown-leather-duffel','["/images/props/brown-leather-duffel.jpg"]'),
  ('brown-leather-suitcase-4','["/images/props/brown-leather-suitcase-4.jpg"]'),
  ('carlos-castaneira-bench','["/images/props/carlos-castaneira-bench.jpg", "/images/props/carlos-castaneira-bench/2.jpg", "/images/props/carlos-castaneira-bench/3.jpg", "/images/props/carlos-castaneira-bench/4.jpg"]'),
  ('carved-wood-frame-mirror','["/images/props/carved-wood-frame-mirror.jpg", "/images/props/carved-wood-frame-mirror/2.jpg"]'),
  ('china-red-wicker','["/images/props/china-red-wicker.jpg", "/images/props/china-red-wicker/2.jpg", "/images/props/china-red-wicker/3.jpg", "/images/props/china-red-wicker/4.jpg"]'),
  ('chrome-floor-lamp-coat-rack','["/images/props/chrome-floor-lamp-coat-rack.jpg", "/images/props/chrome-floor-lamp-coat-rack/2.jpg", "/images/props/chrome-floor-lamp-coat-rack/3.jpg"]'),
  ('clawfoot-bathtub','["/images/props/clawfoot-bathtub.jpg", "/images/props/clawfoot-bathtub/2.jpg"]'),
  ('dark-leather-suitcase-5','["/images/props/dark-leather-suitcase-5.jpg"]'),
  ('decorative-feather','["/images/props/decorative-feather.jpg"]'),
  ('doctors-balance-scale','["/images/props/doctors-balance-scale.jpg", "/images/props/doctors-balance-scale/2.jpg"]'),
  ('double-papasan','["/images/props/double-papasan.jpg", "/images/props/double-papasan/2.jpg", "/images/props/double-papasan/3.jpg", "/images/props/double-papasan/4.jpg", "/images/props/double-papasan/5.jpg", "/images/props/double-papasan/6.jpg"]'),
  ('dress-form-mannequin','["/images/props/dress-form-mannequin.jpg", "/images/props/dress-form-mannequin/2.jpg", "/images/props/dress-form-mannequin/3.jpg"]'),
  ('faux-branches-in-basket','["/images/props/faux-branches-in-basket.jpg", "/images/props/faux-branches-in-basket/2.jpg"]'),
  ('faux-broadleaf-plant','["/images/props/faux-broadleaf-plant.jpg"]'),
  ('faux-bushy-plant','["/images/props/faux-bushy-plant.jpg"]'),
  ('faux-fern-in-basket','["/images/props/faux-fern-in-basket.jpg"]'),
  ('faux-fiddle-leaf-plant','["/images/props/faux-fiddle-leaf-plant.jpg"]'),
  ('faux-grass-plant','["/images/props/faux-grass-plant.jpg"]'),
  ('faux-greenery-planter-boxes','["/images/props/faux-greenery-planter-boxes.jpg", "/images/props/faux-greenery-planter-boxes/2.jpg", "/images/props/faux-greenery-planter-boxes/3.jpg"]'),
  ('faux-monstera-plant','["/images/props/faux-monstera-plant.jpg", "/images/props/faux-monstera-plant/2.jpg"]'),
  ('faux-palm-1','["/images/props/faux-palm-1.jpg"]'),
  ('faux-palm-2','["/images/props/faux-palm-2.jpg"]'),
  ('faux-palm-3','["/images/props/faux-palm-3.jpg"]'),
  ('faux-plant-a','["/images/props/faux-plant-a.jpg"]'),
  ('faux-plant-b','["/images/props/faux-plant-b.jpg"]'),
  ('faux-plant-c','["/images/props/faux-plant-c.jpg"]'),
  ('faux-slim-plant','["/images/props/faux-slim-plant.jpg"]'),
  ('faux-tall-tree','["/images/props/faux-tall-tree.jpg"]'),
  ('faux-willow-plant','["/images/props/faux-willow-plant.jpg"]'),
  ('floor-lamp-with-tray-table','["/images/props/floor-lamp-with-tray-table.jpg", "/images/props/floor-lamp-with-tray-table/2.jpg"]'),
  ('folding-chrome-mirror','["/images/props/folding-chrome-mirror.jpg"]'),
  ('galvanized-metal-toolbox','["/images/props/galvanized-metal-toolbox.jpg", "/images/props/galvanized-metal-toolbox/2.jpg", "/images/props/galvanized-metal-toolbox/3.jpg"]'),
  ('glass-demijohn-pair','["/images/props/glass-demijohn-pair.jpg", "/images/props/glass-demijohn-pair/2.jpg"]'),
  ('gold-oriental-fan-red','["/images/props/gold-oriental-fan-red.jpg"]'),
  ('gold-oval-wall-mirror','["/images/props/gold-oval-wall-mirror.jpg"]'),
  ('gold-peacock-folding-fan','["/images/props/gold-peacock-folding-fan.jpg"]'),
  ('gold-rococo-wall-mirror','["/images/props/gold-rococo-wall-mirror.jpg"]'),
  ('gray-concrete-cube-planter','["/images/props/gray-concrete-cube-planter.jpg", "/images/props/gray-concrete-cube-planter/2.jpg"]'),
  ('gray-cube-planter-on-legs','["/images/props/gray-cube-planter-on-legs.jpg", "/images/props/gray-cube-planter-on-legs/2.jpg", "/images/props/gray-cube-planter-on-legs/3.jpg", "/images/props/gray-cube-planter-on-legs/4.jpg"]'),
  ('gray-leather-loveseat','["/images/props/gray-leather-loveseat.jpg", "/images/props/gray-leather-loveseat/2.jpg", "/images/props/gray-leather-loveseat/3.jpg", "/images/props/gray-leather-loveseat/4.jpg", "/images/props/gray-leather-loveseat/5.jpg", "/images/props/gray-leather-loveseat/6.jpg", "/images/props/gray-leather-loveseat/7.jpg", "/images/props/gray-leather-loveseat/8.jpg", "/images/props/gray-leather-loveseat/9.jpg"]'),
  ('gray-ottoman-cubes-set','["/images/props/gray-ottoman-cubes-set.jpg", "/images/props/gray-ottoman-cubes-set/2.jpg", "/images/props/gray-ottoman-cubes-set/3.jpg", "/images/props/gray-ottoman-cubes-set/4.jpg"]'),
  ('gray-rocker-armchair','["/images/props/gray-rocker-armchair.jpg", "/images/props/gray-rocker-armchair/2.jpg", "/images/props/gray-rocker-armchair/3.jpg", "/images/props/gray-rocker-armchair/4.jpg"]'),
  ('green-military-footlocker','["/images/props/green-military-footlocker.jpg", "/images/props/green-military-footlocker/2.jpg", "/images/props/green-military-footlocker/3.jpg", "/images/props/green-military-footlocker/4.jpg"]'),
  ('green-ornate-table-lamp','["/images/props/green-ornate-table-lamp.jpg"]'),
  ('green-roller','["/images/props/green-roller.jpg", "/images/props/green-roller/2.jpg", "/images/props/green-roller/3.jpg", "/images/props/green-roller/4.jpg"]'),
  ('gymnastics-props-cart','["/images/props/gymnastics-props-cart.jpg", "/images/props/gymnastics-props-cart/2.jpg", "/images/props/gymnastics-props-cart/3.jpg", "/images/props/gymnastics-props-cart/4.jpg", "/images/props/gymnastics-props-cart/5.jpg", "/images/props/gymnastics-props-cart/6.jpg"]'),
  ('hourglass-sand-timer','["/images/props/hourglass-sand-timer.jpg", "/images/props/hourglass-sand-timer/2.jpg"]'),
  ('kitchen-prep-table','["/images/props/kitchen-prep-table.jpg", "/images/props/kitchen-prep-table/2.jpg", "/images/props/kitchen-prep-table/3.jpg", "/images/props/kitchen-prep-table/4.jpg", "/images/props/kitchen-prep-table/5.jpg"]'),
  ('large-leaning-mirror','["/images/props/large-leaning-mirror.jpg"]'),
  ('lazyboy-brown-leather-love-couch','["/images/props/lazyboy-brown-leather-love-couch.jpg", "/images/props/lazyboy-brown-leather-love-couch/2.jpg", "/images/props/lazyboy-brown-leather-love-couch/3.jpg", "/images/props/lazyboy-brown-leather-love-couch/4.jpg"]'),
  ('leather-brown-bench','["/images/props/leather-brown-bench.jpg", "/images/props/leather-brown-bench/2.jpg", "/images/props/leather-brown-bench/3.jpg", "/images/props/leather-brown-bench/4.jpg"]'),
  ('leather-brown-metal-bench','["/images/props/leather-brown-metal-bench.jpg", "/images/props/leather-brown-metal-bench/2.jpg", "/images/props/leather-brown-metal-bench/3.jpg", "/images/props/leather-brown-metal-bench/4.jpg"]'),
  ('leather-round-hat-box','["/images/props/leather-round-hat-box.jpg", "/images/props/leather-round-hat-box/2.jpg"]'),
  ('leather-suitcase-2','["/images/props/leather-suitcase-2.jpg"]'),
  ('live-edge-wood-slab-table','["/images/props/live-edge-wood-slab-table.jpg", "/images/props/live-edge-wood-slab-table/2.jpg"]'),
  ('medieval-sword','["/images/props/medieval-sword.jpg", "/images/props/medieval-sword/2.jpg"]'),
  ('metal-folding-chairs','["/images/props/metal-folding-chairs.jpg", "/images/props/metal-folding-chairs/2.jpg", "/images/props/metal-folding-chairs/3.jpg", "/images/props/metal-folding-chairs/4.jpg", "/images/props/metal-folding-chairs/5.jpg", "/images/props/metal-folding-chairs/6.jpg", "/images/props/metal-folding-chairs/7.jpg"]'),
  ('mid-century-desk','["/images/props/mid-century-desk.jpg", "/images/props/mid-century-desk/2.jpg", "/images/props/mid-century-desk/3.jpg", "/images/props/mid-century-desk/4.jpg"]'),
  ('mid-century-duo-table','["/images/props/mid-century-duo-table.jpg", "/images/props/mid-century-duo-table/2.jpg", "/images/props/mid-century-duo-table/3.jpg"]'),
  ('mid-century-side-table','["/images/props/mid-century-side-table.jpg", "/images/props/mid-century-side-table/2.jpg", "/images/props/mid-century-side-table/3.jpg", "/images/props/mid-century-side-table/4.jpg"]'),
  ('mirror-corner-panel','["/images/props/mirror-corner-panel.jpg"]'),
  ('modern-curve-rocker','["/images/props/modern-curve-rocker.jpg", "/images/props/modern-curve-rocker/2.jpg", "/images/props/modern-curve-rocker/3.jpg", "/images/props/modern-curve-rocker/4.jpg"]'),
  ('modern-leather-couch','["/images/props/modern-leather-couch.jpg", "/images/props/modern-leather-couch/2.jpg", "/images/props/modern-leather-couch/3.jpg", "/images/props/modern-leather-couch/4.jpg", "/images/props/modern-leather-couch/5.jpg", "/images/props/modern-leather-couch/6.jpg", "/images/props/modern-leather-couch/7.jpg", "/images/props/modern-leather-couch/8.jpg"]'),
  ('mustard-vintage-armchair','["/images/props/mustard-vintage-armchair.jpg", "/images/props/mustard-vintage-armchair/2.jpg", "/images/props/mustard-vintage-armchair/3.jpg", "/images/props/mustard-vintage-armchair/4.jpg"]'),
  ('neon-open-sign','["/images/props/neon-open-sign.jpg"]'),
  ('neon-skateboard','["/images/props/neon-skateboard.jpg", "/images/props/neon-skateboard/2.jpg"]'),
  ('oak-wall-crank-telephone-2','["/images/props/oak-wall-crank-telephone-2.jpg", "/images/props/oak-wall-crank-telephone-2/2.jpg", "/images/props/oak-wall-crank-telephone-2/3.jpg"]'),
  ('old-warehouse-chair','["/images/props/old-warehouse-chair.jpg", "/images/props/old-warehouse-chair/2.jpg", "/images/props/old-warehouse-chair/3.jpg", "/images/props/old-warehouse-chair/4.jpg"]'),
  ('oriental-art-panel-pair','["/images/props/oriental-art-panel-pair.jpg"]'),
  ('oriental-art-panel-single','["/images/props/oriental-art-panel-single.jpg"]'),
  ('oriental-bird-art-panel','["/images/props/oriental-bird-art-panel.jpg"]'),
  ('overhead-projector','["/images/props/overhead-projector.jpg", "/images/props/overhead-projector/2.jpg", "/images/props/overhead-projector/3.jpg", "/images/props/overhead-projector/4.jpg"]'),
  ('pampas-grass-in-brass-vase','["/images/props/pampas-grass-in-brass-vase.jpg", "/images/props/pampas-grass-in-brass-vase/2.jpg", "/images/props/pampas-grass-in-brass-vase/3.jpg", "/images/props/pampas-grass-in-brass-vase/4.jpg"]'),
  ('patina-steer-skull','["/images/props/patina-steer-skull.jpg"]'),
  ('peacock-chair','["/images/props/peacock-chair.jpg", "/images/props/peacock-chair/2.jpg", "/images/props/peacock-chair/3.jpg", "/images/props/peacock-chair/4.jpg"]'),
  ('peacock-feather','["/images/props/peacock-feather.jpg"]'),
  ('plaid-folding-lounge-chair','["/images/props/plaid-folding-lounge-chair.jpg", "/images/props/plaid-folding-lounge-chair/2.jpg", "/images/props/plaid-folding-lounge-chair/3.jpg"]'),
  ('potted-palms-cluster-2','["/images/props/potted-palms-cluster-2.jpg"]'),
  ('potted-plants-cluster-1','["/images/props/potted-plants-cluster-1.jpg"]'),
  ('purple-vintage-recliner','["/images/props/purple-vintage-recliner.jpg", "/images/props/purple-vintage-recliner/2.jpg", "/images/props/purple-vintage-recliner/3.jpg", "/images/props/purple-vintage-recliner/4.jpg", "/images/props/purple-vintage-recliner/5.jpg"]'),
  ('rattan-ball-lantern','["/images/props/rattan-ball-lantern.jpg"]'),
  ('rattan-folding-screen','["/images/props/rattan-folding-screen.jpg", "/images/props/rattan-folding-screen/2.jpg", "/images/props/rattan-folding-screen/3.jpg"]'),
  ('rattan-lantern-with-handle','["/images/props/rattan-lantern-with-handle.jpg"]'),
  ('rattan-patio-chairs','["/images/props/rattan-patio-chairs.jpg", "/images/props/rattan-patio-chairs/2.jpg", "/images/props/rattan-patio-chairs/3.jpg", "/images/props/rattan-patio-chairs/4.jpg", "/images/props/rattan-patio-chairs/5.jpg"]'),
  ('rattan-rocker','["/images/props/rattan-rocker.jpg", "/images/props/rattan-rocker/2.jpg", "/images/props/rattan-rocker/3.jpg", "/images/props/rattan-rocker/4.jpg"]'),
  ('red-coca-cola-mini-fridge','["/images/props/red-coca-cola-mini-fridge.jpg", "/images/props/red-coca-cola-mini-fridge/2.jpg", "/images/props/red-coca-cola-mini-fridge/3.jpg"]'),
  ('red-glass-vase-with-wheat','["/images/props/red-glass-vase-with-wheat.jpg", "/images/props/red-glass-vase-with-wheat/2.jpg", "/images/props/red-glass-vase-with-wheat/3.jpg"]'),
  ('red-hurricane-lantern','["/images/props/red-hurricane-lantern.jpg"]'),
  ('red-relaxer','["/images/props/red-relaxer.jpg", "/images/props/red-relaxer/2.jpg", "/images/props/red-relaxer/3.jpg", "/images/props/red-relaxer/4.jpg"]'),
  ('red-side-chair','["/images/props/red-side-chair.jpg", "/images/props/red-side-chair/2.jpg", "/images/props/red-side-chair/3.jpg", "/images/props/red-side-chair/4.jpg", "/images/props/red-side-chair/5.jpg"]'),
  ('red-tassel-ottoman','["/images/props/red-tassel-ottoman.jpg", "/images/props/red-tassel-ottoman/2.jpg"]'),
  ('rolled-leather-bedroll','["/images/props/rolled-leather-bedroll.jpg"]'),
  ('rolling-blue-executive','["/images/props/rolling-blue-executive.jpg", "/images/props/rolling-blue-executive/2.jpg", "/images/props/rolling-blue-executive/3.jpg", "/images/props/rolling-blue-executive/4.jpg"]'),
  ('rough-console-farrm-table','["/images/props/rough-console-farrm-table.jpg", "/images/props/rough-console-farrm-table/2.jpg", "/images/props/rough-console-farrm-table/3.jpg"]'),
  ('round-rattan-striped-pouf','["/images/props/round-rattan-striped-pouf.jpg", "/images/props/round-rattan-striped-pouf/2.jpg"]'),
  ('round-rattan-wall-mirror','["/images/props/round-rattan-wall-mirror.jpg"]'),
  ('round-woven-storage-box','["/images/props/round-woven-storage-box.jpg"]'),
  ('rustic-timber-pedestal','["/images/props/rustic-timber-pedestal.jpg"]'),
  ('skull-bookend','["/images/props/skull-bookend.jpg"]'),
  ('small-leather-box','["/images/props/small-leather-box.jpg"]'),
  ('small-wood-chest','["/images/props/small-wood-chest.jpg"]'),
  ('soft-blue','["/images/props/soft-blue.jpg", "/images/props/soft-blue/2.jpg", "/images/props/soft-blue/3.jpg", "/images/props/soft-blue/4.jpg"]'),
  ('spells-prop-spellbook','["/images/props/spells-prop-spellbook.jpg", "/images/props/spells-prop-spellbook/2.jpg"]'),
  ('stacked-vintage-trunks-set','["/images/props/stacked-vintage-trunks-set.jpg", "/images/props/stacked-vintage-trunks-set/2.jpg"]'),
  ('steel-and-brown-leather','["/images/props/steel-and-brown-leather.jpg", "/images/props/steel-and-brown-leather/2.jpg", "/images/props/steel-and-brown-leather/3.jpg", "/images/props/steel-and-brown-leather/4.jpg"]'),
  ('steer-skull-canvas-art','["/images/props/steer-skull-canvas-art.jpg"]'),
  ('step-box','["/images/props/step-box.jpg", "/images/props/step-box/2.jpg", "/images/props/step-box/3.jpg", "/images/props/step-box/4.jpg"]'),
  ('stripe-vintage-bench','["/images/props/stripe-vintage-bench.jpg", "/images/props/stripe-vintage-bench/2.jpg", "/images/props/stripe-vintage-bench/3.jpg", "/images/props/stripe-vintage-bench/4.jpg"]'),
  ('table-lamp-with-brown-shade','["/images/props/table-lamp-with-brown-shade.jpg", "/images/props/table-lamp-with-brown-shade/2.jpg"]'),
  ('tall-chrome-mirror-panel-1','["/images/props/tall-chrome-mirror-panel-1.jpg", "/images/props/tall-chrome-mirror-panel-1/2.jpg"]'),
  ('tall-mirror-panel-2','["/images/props/tall-mirror-panel-2.jpg"]'),
  ('tall-wicker-case','["/images/props/tall-wicker-case.jpg"]'),
  ('tan-leather-suitcase-1','["/images/props/tan-leather-suitcase-1.jpg", "/images/props/tan-leather-suitcase-1/2.jpg"]'),
  ('tan-leather-suitcase-3','["/images/props/tan-leather-suitcase-3.jpg"]'),
  ('teal-electric-typewriter','["/images/props/teal-electric-typewriter.jpg", "/images/props/teal-electric-typewriter/2.jpg", "/images/props/teal-electric-typewriter/3.jpg"]'),
  ('teal-vintage-futon','["/images/props/teal-vintage-futon.jpg", "/images/props/teal-vintage-futon/2.jpg", "/images/props/teal-vintage-futon/3.jpg", "/images/props/teal-vintage-futon/4.jpg", "/images/props/teal-vintage-futon/5.jpg", "/images/props/teal-vintage-futon/6.jpg", "/images/props/teal-vintage-futon/7.jpg", "/images/props/teal-vintage-futon/8.jpg"]'),
  ('treadle-sewing-machine-table-1','["/images/props/treadle-sewing-machine-table-1.jpg", "/images/props/treadle-sewing-machine-table-1/2.jpg", "/images/props/treadle-sewing-machine-table-1/3.jpg"]'),
  ('treadle-sewing-machine-table-2','["/images/props/treadle-sewing-machine-table-2.jpg", "/images/props/treadle-sewing-machine-table-2/2.jpg", "/images/props/treadle-sewing-machine-table-2/3.jpg", "/images/props/treadle-sewing-machine-table-2/4.jpg"]'),
  ('various-stools','["/images/props/various-stools.jpg", "/images/props/various-stools/2.jpg"]'),
  ('verdigris-metal-pot','["/images/props/verdigris-metal-pot.jpg", "/images/props/verdigris-metal-pot/2.jpg", "/images/props/verdigris-metal-pot/3.jpg", "/images/props/verdigris-metal-pot/4.jpg"]'),
  ('victorian-beige','["/images/props/victorian-beige.jpg", "/images/props/victorian-beige/2.jpg", "/images/props/victorian-beige/3.jpg", "/images/props/victorian-beige/4.jpg"]'),
  ('victorian-couch','["/images/props/victorian-couch.jpg", "/images/props/victorian-couch/2.jpg", "/images/props/victorian-couch/3.jpg", "/images/props/victorian-couch/4.jpg", "/images/props/victorian-couch/5.jpg"]'),
  ('victorian-tan-highchair','["/images/props/victorian-tan-highchair.jpg", "/images/props/victorian-tan-highchair/2.jpg", "/images/props/victorian-tan-highchair/3.jpg"]'),
  ('vintage-bellows-camera-2','["/images/props/vintage-bellows-camera-2.jpg"]'),
  ('vintage-bicycle','["/images/props/vintage-bicycle.jpg", "/images/props/vintage-bicycle/2.jpg"]'),
  ('vintage-blue-and-wood','["/images/props/vintage-blue-and-wood.jpg", "/images/props/vintage-blue-and-wood/2.jpg", "/images/props/vintage-blue-and-wood/3.jpg", "/images/props/vintage-blue-and-wood/4.jpg"]'),
  ('vintage-boombox','["/images/props/vintage-boombox.jpg", "/images/props/vintage-boombox/2.jpg", "/images/props/vintage-boombox/3.jpg"]'),
  ('vintage-box-camera','["/images/props/vintage-box-camera.jpg"]'),
  ('vintage-cathedral-radio','["/images/props/vintage-cathedral-radio.jpg", "/images/props/vintage-cathedral-radio/2.jpg", "/images/props/vintage-cathedral-radio/3.jpg"]'),
  ('vintage-chrome-electric-iron','["/images/props/vintage-chrome-electric-iron.jpg", "/images/props/vintage-chrome-electric-iron/2.jpg", "/images/props/vintage-chrome-electric-iron/3.jpg", "/images/props/vintage-chrome-electric-iron/4.jpg"]'),
  ('vintage-eliptical','["/images/props/vintage-eliptical.jpg", "/images/props/vintage-eliptical/2.jpg", "/images/props/vintage-eliptical/3.jpg", "/images/props/vintage-eliptical/4.jpg", "/images/props/vintage-eliptical/5.jpg"]'),
  ('vintage-folding-camera-1','["/images/props/vintage-folding-camera-1.jpg"]'),
  ('vintage-green','["/images/props/vintage-green.jpg", "/images/props/vintage-green/2.jpg", "/images/props/vintage-green/3.jpg", "/images/props/vintage-green/4.jpg", "/images/props/vintage-green/5.jpg", "/images/props/vintage-green/6.jpg", "/images/props/vintage-green/7.jpg", "/images/props/vintage-green/8.jpg"]'),
  ('vintage-platform-scale','["/images/props/vintage-platform-scale.jpg"]'),
  ('vintage-press-camera-3','["/images/props/vintage-press-camera-3.jpg", "/images/props/vintage-press-camera-3/2.jpg"]'),
  ('vintage-rocker','["/images/props/vintage-rocker.jpg", "/images/props/vintage-rocker/2.jpg", "/images/props/vintage-rocker/3.jpg", "/images/props/vintage-rocker/4.jpg"]'),
  ('vintage-wheelchair','["/images/props/vintage-wheelchair.jpg", "/images/props/vintage-wheelchair/2.jpg", "/images/props/vintage-wheelchair/3.jpg", "/images/props/vintage-wheelchair/4.jpg", "/images/props/vintage-wheelchair/5.jpg", "/images/props/vintage-wheelchair/6.jpg"]'),
  ('wall-crank-telephone-1','["/images/props/wall-crank-telephone-1.jpg"]'),
  ('weight-plate-tree','["/images/props/weight-plate-tree.jpg", "/images/props/weight-plate-tree/2.jpg", "/images/props/weight-plate-tree/3.jpg"]'),
  ('white-angel-wings','["/images/props/white-angel-wings.jpg", "/images/props/white-angel-wings/2.jpg"]'),
  ('white-cube','["/images/props/white-cube.jpg", "/images/props/white-cube/2.jpg"]'),
  ('white-female-mannequin','["/images/props/white-female-mannequin.jpg", "/images/props/white-female-mannequin/2.jpg", "/images/props/white-female-mannequin/3.jpg"]'),
  ('white-medical-privacy-screen','["/images/props/white-medical-privacy-screen.jpg", "/images/props/white-medical-privacy-screen/2.jpg"]'),
  ('white-nightstand-1','["/images/props/white-nightstand-1.jpg", "/images/props/white-nightstand-1/2.jpg"]'),
  ('white-nightstand-2','["/images/props/white-nightstand-2.jpg", "/images/props/white-nightstand-2/2.jpg"]'),
  ('white-orthopedic-back-brace','["/images/props/white-orthopedic-back-brace.jpg", "/images/props/white-orthopedic-back-brace/2.jpg", "/images/props/white-orthopedic-back-brace/3.jpg", "/images/props/white-orthopedic-back-brace/4.jpg"]'),
  ('white-pedestal-plinth','["/images/props/white-pedestal-plinth.jpg", "/images/props/white-pedestal-plinth/2.jpg"]'),
  ('wicker-basket-ottoman','["/images/props/wicker-basket-ottoman.jpg"]'),
  ('wicker-box','["/images/props/wicker-box.jpg"]'),
  ('wicker-dome-chest-1','["/images/props/wicker-dome-chest-1.jpg"]'),
  ('wicker-dome-chest-2','["/images/props/wicker-dome-chest-2.jpg"]'),
  ('wicker-high-chair','["/images/props/wicker-high-chair.jpg", "/images/props/wicker-high-chair/2.jpg", "/images/props/wicker-high-chair/3.jpg"]'),
  ('wicker-trunk-1','["/images/props/wicker-trunk-1.jpg", "/images/props/wicker-trunk-1/2.jpg"]'),
  ('wicker-trunk-2-open','["/images/props/wicker-trunk-2-open.jpg"]'),
  ('wood-farm-side-table','["/images/props/wood-farm-side-table.jpg"]'),
  ('wood-folding-screen-2','["/images/props/wood-folding-screen-2.jpg"]'),
  ('wood-interlocking-puzzle','["/images/props/wood-interlocking-puzzle.jpg"]'),
  ('wood-louvered-folding-screen-1','["/images/props/wood-louvered-folding-screen-1.jpg", "/images/props/wood-louvered-folding-screen-1/2.jpg", "/images/props/wood-louvered-folding-screen-1/3.jpg"]'),
  ('wood-mantel-clock-1','["/images/props/wood-mantel-clock-1.jpg", "/images/props/wood-mantel-clock-1/2.jpg"]'),
  ('wood-mantel-clock-2','["/images/props/wood-mantel-clock-2.jpg"]'),
  ('wood-metronome','["/images/props/wood-metronome.jpg", "/images/props/wood-metronome/2.jpg"]'),
  ('wood-tripod-floor-lamp','["/images/props/wood-tripod-floor-lamp.jpg", "/images/props/wood-tripod-floor-lamp/2.jpg"]'),
  ('wooden-lap-desk','["/images/props/wooden-lap-desk.jpg"]'),
  ('wooden-phonograph-box','["/images/props/wooden-phonograph-box.jpg", "/images/props/wooden-phonograph-box/2.jpg"]'),
  ('wooden-sleigh','["/images/props/wooden-sleigh.jpg", "/images/props/wooden-sleigh/2.jpg"]'),
  ('world-globe-1','["/images/props/world-globe-1.jpg", "/images/props/world-globe-1/2.jpg", "/images/props/world-globe-1/3.jpg"]'),
  ('world-globe-2','["/images/props/world-globe-2.jpg"]'),
  ('woven-rattan-box','["/images/props/woven-rattan-box.jpg"]'),
  ('woven-seagrass-mat','["/images/props/woven-seagrass-mat.jpg"]')
) as v(slug, gallery)
where p.image_url = '/images/props/' || v.slug || '.jpg';

create unique index if not exists props_slug_idx on props(slug);
