-- 025: merge + delete duplicate prop listings
insert into props (name,category,image_url,is_active,sort_order,slug,gallery) values ('World Globe','Misc','/images/props/world-globe-1.jpg',true,500,'world-globe','["/images/props/world-globe-1.jpg", "/images/props/world-globe-1/2.jpg", "/images/props/world-globe-1/3.jpg", "/images/props/world-globe-2.jpg"]'::jsonb);
delete from props where slug in ('world-globe-1','world-globe-2');
insert into props (name,category,image_url,is_active,sort_order,slug,gallery) values ('Wicker Trunk','Misc','/images/props/wicker-trunk-1.jpg',true,500,'wicker-trunk','["/images/props/wicker-trunk-1.jpg", "/images/props/wicker-trunk-1/2.jpg", "/images/props/wicker-trunk-2-open.jpg", "/images/props/wicker-box.jpg"]'::jsonb);
delete from props where slug in ('wicker-trunk-1','wicker-trunk-2-open','wicker-box');
insert into props (name,category,image_url,is_active,sort_order,slug,gallery) values ('Black Rotary Telephone','Misc','/images/props/black-rotary-telephone-1.jpg',true,500,'black-rotary-telephone','["/images/props/black-rotary-telephone-1.jpg", "/images/props/black-rotary-telephone-1/2.jpg", "/images/props/black-rotary-telephone-2.jpg", "/images/props/black-rotary-telephone-2/2.jpg", "/images/props/black-rotary-telephone-2/3.jpg"]'::jsonb);
delete from props where slug in ('black-rotary-telephone-1','black-rotary-telephone-2');
insert into props (name,category,image_url,is_active,sort_order,slug,gallery) values ('Wood Mantel Clock','Misc','/images/props/wood-mantel-clock-1.jpg',true,500,'wood-mantel-clock','["/images/props/wood-mantel-clock-1.jpg", "/images/props/wood-mantel-clock-1/2.jpg", "/images/props/wood-mantel-clock-2.jpg"]'::jsonb);
delete from props where slug in ('wood-mantel-clock-1','wood-mantel-clock-2');
insert into props (name,category,image_url,is_active,sort_order,slug,gallery) values ('Wicker Dome Chest','Misc','/images/props/wicker-dome-chest-1.jpg',true,500,'wicker-dome-chest','["/images/props/wicker-dome-chest-1.jpg", "/images/props/wicker-dome-chest-2.jpg", "/images/props/small-leather-box.jpg", "/images/props/small-wood-chest.jpg"]'::jsonb);
delete from props where slug in ('wicker-dome-chest-1','wicker-dome-chest-2','small-leather-box','small-wood-chest');
insert into props (name,category,image_url,is_active,sort_order,slug,gallery) values ('Gray Cubes','Misc','/images/props/gray-concrete-cube-planter.jpg',true,500,'gray-cubes','["/images/props/gray-concrete-cube-planter.jpg", "/images/props/gray-concrete-cube-planter/2.jpg", "/images/props/gray-cube-planter-on-legs.jpg", "/images/props/gray-cube-planter-on-legs/2.jpg", "/images/props/gray-cube-planter-on-legs/3.jpg", "/images/props/gray-cube-planter-on-legs/4.jpg", "/images/props/gray-ottoman-cubes-set.jpg", "/images/props/gray-ottoman-cubes-set/2.jpg", "/images/props/gray-ottoman-cubes-set/3.jpg", "/images/props/gray-ottoman-cubes-set/4.jpg"]'::jsonb);
delete from props where slug in ('gray-concrete-cube-planter','gray-cube-planter-on-legs','gray-ottoman-cubes-set');
insert into props (name,category,image_url,is_active,sort_order,slug,gallery) values ('Potted Plant Cluster','Misc','/images/props/potted-plants-cluster-1.jpg',true,500,'potted-plant-cluster','["/images/props/potted-plants-cluster-1.jpg", "/images/props/potted-palms-cluster-2.jpg"]'::jsonb);
delete from props where slug in ('potted-plants-cluster-1','potted-palms-cluster-2');
insert into props (name,category,image_url,is_active,sort_order,slug,gallery) values ('White Nightstand','Tables','/images/props/white-nightstand-1.jpg',true,500,'white-nightstand','["/images/props/white-nightstand-1.jpg", "/images/props/white-nightstand-1/2.jpg", "/images/props/white-nightstand-2.jpg", "/images/props/white-nightstand-2/2.jpg"]'::jsonb);
delete from props where slug in ('white-nightstand-1','white-nightstand-2');
delete from props where slug in ('oak-wall-crank-telephone-2','wall-crank-telephone-1','tall-chrome-mirror-panel-1','tall-mirror-panel-2','treadle-sewing-machine-table-1','treadle-sewing-machine-table-2','tan-leather-suitcase-1','tan-leather-suitcase-3','leather-suitcase-2','brown-leather-suitcase-4','dark-leather-suitcase-5');
