// Support Center content (2026-10-07). Shown on /support (public; the App Store
// + Google Play support URL) and /account/support (Help & Support in the
// account rail). Rendered by components/SupportCenter.tsx.
//
// Two kinds of article, same shape:
//   answer-only (policy, from June's knowledge base, agent_kb, as of 2026-10-07)
//   step-by-step guides (written from the actual screens; labels are the
//   literal on-screen text). When a screen or policy changes, update this file
//   AND June's KB — the site and June must never say different things.
//
// No phone number on purpose (Teddy, 2026-10-07): support goes through the
// Contact Support ticket form, and at the studio through GET THE TEAM.
// No prices either: rates change and member/guest pricing differs.
// [label](/path) in any text becomes a link. /support?a=<slug> opens an article.

export type Article = {
  slug: string
  q: string
  a?: string          // short answer / intro
  steps?: string[]    // numbered steps (literal on-screen labels)
  notes?: string[]    // good-to-know bullets
  tags?: string
  popular?: boolean
}
export type Category = { id: string; title: string; blurb: string; icon: string; articles: Article[] }

export const SUPPORT_EMAIL = 'info@madekulture.com'

// Navigation shorthand used in many guides.
const SETTINGS = 'Open Settings — the gear at the bottom of the left menu. On phones tap More (•••) in the bottom bar, then Settings.'

export const CATEGORIES: Category[] = [
  {
    id: 'start', title: 'Getting started', icon: 'spark', blurb: 'Accounts, signing in and the app',
    articles: [
      { slug: 'create-account', q: 'How do I create an account?', tags: 'sign up register join new member free', popular: true,
        a: 'Accounts are free. They give you the member booking rate, saved-card checkout, your bookings and studio credit in one place, and the creative directory.',
        steps: [
          'Go to [Sign up](/signup), or tap Create an account on the sign-in page.',
          'Tap SIGN UP WITH GOOGLE or SIGN UP WITH APPLE — or use the email form below OR.',
          'Under “What brings you here?” pick Just booking, Creative, Vendor or Brand.',
          'Fill in your name, Email address and Phone number (Instagram is optional).',
          'Choose a password (at least 6 characters), confirm it, and tap CREATE ACCOUNT.',
          'Open the confirmation email and click the link to activate your account.',
        ],
        notes: ['You can’t sign in with email until you’ve clicked the confirmation link.', 'Google and Apple sign-ups don’t need the confirmation email.'] },
      { slug: 'sign-in', q: 'How do I sign in?', tags: 'log in login google apple password',
        steps: [
          'Go to [Sign in](/login).',
          'Tap CONTINUE WITH GOOGLE or CONTINUE WITH APPLE — or enter your Email address and Password and tap SIGN IN.',
        ],
        notes: ['Signed up with Google or Apple? Use that same button — those accounts don’t have a password.', 'In the Made Kulture app, Google and Apple open a sign-in sheet; finish there and you’re brought back in.'] },
      { slug: 'welcome-step', q: 'Why am I on a WELCOME screen after signing in?', tags: 'welcome onboarding phone number required google',
        a: 'New accounts finish a short welcome step before using the account area.',
        steps: [
          'Confirm Your name.',
          'Enter your Mobile number (10 digits).',
          'Optionally pick up to 3 roles under “What do you do?”, add your Instagram, and choose whether to be shown in the member directory.',
          'Tap SAVE & CONTINUE (or Skip roles for now).',
        ],
        notes: ['Name and phone are required even if you skip roles.', 'You can change all of this later in Settings.'] },
      { slug: 'forgot-password', q: 'I forgot my password', tags: 'reset password forgot locked out cant log in',
        steps: [
          'On the sign-in page tap Forgot password?',
          'Enter your Email address and tap SEND RESET LINK.',
          'Open the link in the email, enter a New password and Confirm password, then tap UPDATE PASSWORD.',
        ],
        notes: ['Signed up with Google or Apple? You don’t have a password — just use that button.', 'Still stuck? Contact support below.'] },
      { slug: 'get-app', q: 'How do I get the Made Kulture app?', tags: 'app iphone android download install',
        a: 'Download Made Kulture from the App Store or Google Play and sign in with your account. On a computer or Android you can also install it straight from the website: [Get the app](/account/app).' },
      { slug: 'notifications', q: 'How do I turn notifications on or off?', tags: 'notifications push alerts test',
        steps: [
          SETTINGS,
          'Choose Get the app.',
          'Tap TURN ON NOTIFICATIONS and allow them when your phone asks. Tap SEND A TEST to check.',
          'To stop them on that device, tap TURN OFF ON THIS DEVICE — or turn them off in your phone’s Settings → Made Kulture → Notifications.',
        ],
        notes: ['Notifications are per device — turn them on for each phone or computer.', 'Email notifications keep working either way.', 'Text and email alerts for messages and booking reminders are in Settings → Directory & notifications.'] },
      { slug: 'find-things', q: 'Where is everything in my account?', tags: 'menu navigation where settings more',
        a: 'Desktop: the left menu has Dashboard, My Bookings, Directory, Castings, Messages and Profile, with Help & Support and Settings at the bottom. Phones: the bottom bar has Dashboard, Directory, Castings, Messages and Profile; tap More (•••) for My Bookings, Help & Support, Settings and Sign out. Inside Settings, phones show the sections as a row you scroll sideways.' },
      { slug: 'dashboard', q: 'What does my Dashboard show?', tags: 'dashboard home overview',
        a: 'Your Dashboard shows your Plus card, three tiles — Upcoming bookings, Studio credit, and Account standing with Booking flexibility — plus shortcuts to Book a set, View all bookings and Edit profile.' },
      { slug: 'theme', q: 'How do I switch between light and dark mode?', tags: 'dark mode light mode theme',
        steps: ['Desktop: tap Dark mode / Light mode at the bottom of the left menu.', 'Phone: tap the sun / moon icon at the top right.'],
        notes: ['Your choice is saved on that device.'] },
      { slug: 'sign-out', q: 'How do I sign out?', tags: 'log out sign out',
        steps: ['Desktop: tap Sign out at the bottom of the left menu.', 'Phone: tap More (•••), then Sign out.'] },
    ],
  },
  {
    id: 'booking', title: 'Booking a set', icon: 'cal', blurb: 'Sets, buyouts, guests and equipment',
    articles: [
      { slug: 'book-set', q: 'How do I book a set?', tags: 'book reserve individual set shared hourly', popular: true,
        steps: [
          'Go to [Book](/book) and tap INDIVIDUAL SET.',
          'On HOW MANY PEOPLE? set your total party — everyone on site — and tap CONTINUE.',
          'On CHOOSE YOUR SET tap a set (VIEW DETAILS shows photos), then tap CONTINUE below the sets.',
          'PICK A DATE, then on SELECT YOUR TIME tap your start time, then your end time.',
          'On ADD EQUIPMENT add any gear (optional).',
          'On YOUR DETAILS fill in your name, email and phone and tick the required boxes.',
          'On CONFIRM & PAY check the summary and tap CONFIRM & PAY.',
        ],
        notes: ['Bookings run in 30-minute steps, with each set’s minimum shown on its card.', 'Times marked BOOKED or CLOSED can’t be picked. Picked the wrong start? Tap ↺ RESET TIME.', 'Shared studio hours are 9am–10pm, every day.'] },
      { slug: 'advance', q: 'How far ahead do I need to book?', tags: 'advance notice 48 hours last minute same day',
        a: 'At least 48 hours ahead — the earliest date on the calendar is two days from today. Made Kulture Plus members can also book or request times inside that window. [About Plus](/plus)' },
      { slug: 'set-vs-buyout', q: 'What’s the difference between a set and a full studio buyout?', tags: 'shared private warehouse buyout takeover',
        a: 'A set booking is one individual set during shared studio hours, for up to 5 people — other customers may be using other sets at the same time. A Full Studio Takeover gives you the entire warehouse, private, for up to 30 people.' },
      { slug: 'buyout', q: 'How do I book the whole studio?', tags: 'buyout full studio takeover warehouse private event',
        steps: [
          'Go to [Book](/book) and tap FULL STUDIO TAKEOVER.',
          'PICK A DATE, then tap a start and end time (4-hour minimum).',
          'Add equipment if you want, fill in YOUR DETAILS, tick the Full Warehouse Rental Agreement & Waiver, and pay.',
        ],
        notes: ['Gold times mean a set is already booked in that window — you can request the takeover and share the floor with that booking (sign-in required).', 'Takeovers can’t be rescheduled online — contact support.', 'Groups over 30: contact support.'] },
      { slug: 'party-size', q: 'How many people can I bring?', tags: 'guests party size people limit extra guest fee crew', popular: true,
        a: 'Up to 5 people per set, counting everyone — photographers, models, stylists, assistants, clients and children. A party of 6–7 can stay on one set with a per-person hourly fee added at checkout. Bigger groups need more sets at the same time, or a Full Studio Takeover (up to 30).',
        notes: ['The HOW MANY PEOPLE? step tells you what fits and adds any extra-guest fee for you.', 'Extra guests aren’t allowed on the premises even if they stay off set. Undeclared guests over the limit may be charged to the card on file.', 'Party grows during the session? Tell the team — extra people are charged at the same hourly rate.'] },
      { slug: 'multi-set', q: 'Can I book more than one set at once?', tags: 'multiple sets add another set same booking',
        steps: [
          'After picking your first set’s time, tap + ADD ANOTHER SET.',
          'Choose the next set and its time. Your sets list under SETS IN THIS BOOKING (× removes one).',
          'Tap CONTINUE to check out — one payment, one door code.',
        ],
        notes: ['All sets in one booking are on the same day.', 'Large parties that need several sets are locked to the same time.'] },
      { slug: 'equipment', q: 'How do I add equipment or extra lights?', tags: 'equipment gear lights strobe haze fog projector camera rental add-ons',
        steps: [
          'On the ADD EQUIPMENT step, search or open LIGHTING, MODIFIERS, SPECIAL EFFECTS or CAMERA.',
          'Add items — they appear under YOUR KIT, where − / + changes the quantity.',
          'Tap CONTINUE.',
        ],
        notes: ['Every set already includes one Amaran 200x light; extra lights are listed with the equipment.', 'Equipment is for in-studio use only.'] },
      { slug: 'whats-included', q: 'What’s included with a set?', tags: 'included props light',
        a: 'One Amaran 200x LED light and the set’s props. Props are first come, first served during shared hours and must go back where you found them before your session ends.' },
      { slug: 'details-checkboxes', q: 'Why can’t I continue past YOUR DETAILS?', tags: 'continue disabled checkbox agreement waiver sms consent',
        a: 'CONTINUE stays off until your name, email and phone are filled in and every required box is ticked: text-message consent (door codes and reminders come by text), the Rental Agreement & Waiver, and — for sets — the extra-guest acknowledgment.' },
      { slug: 'switch-sets', q: 'Can I switch sets during my session?', tags: 'change set move set',
        a: 'No — a booking is for that specific set. To use more than one, book each set (or a Full Studio Takeover).' },
      { slug: 'hours-location', q: 'What are your hours and where are you?', tags: 'address location hours open',
        a: 'Shared studio hours are 9am–10pm, Monday through Sunday, at 4825 Gulf Freeway, Houston TX 77023. Bookings outside those hours are available on request at the full warehouse rate — contact support.' },
      { slug: 'price', q: 'How much does it cost?', tags: 'price rate cost hourly member guest',
        a: 'Each set’s hourly rate is on its page and at checkout. Members with a free account pay a lower rate than guests. [See the sets](/sets)' },
      { slug: 'plus-short-notice', q: 'How do I book inside 48 hours? (Plus)', tags: 'plus short notice request last minute gold times',
        steps: [
          'On [Book](/book), Plus members can pick today or tomorrow.',
          'On SELECT YOUR TIME, white times are open — book them as normal. Gold times aren’t open yet — tap one to request it.',
          'Choose HOW LONG?, pick a card under CHARGE WHICH CARD?, tick the consent box, and tap SEND REQUEST.',
        ],
        notes: ['Nothing is charged unless the studio approves. Then your card is charged and you get a confirmation by text and email.', 'An open-looking time isn’t a guarantee — the studio may be unstaffed.'] },
      { slug: 'guest-checkout', q: 'Do I need an account to book?', tags: 'guest checkout account member rate',
        a: 'No — you can book as a guest. Guests pay the guest rate and manage their booking from the link in their confirmation email. A free account gets the member rate and keeps everything in My Bookings. [Create an account](/signup)' },
      { slug: 'after-booking', q: 'What happens after I book?', tags: 'confirmation email text booked',
        a: 'You get a confirmation email and text with your set, date, time and total, a link to your card receipt, and a Check in & get my code button. Your door code is not in the confirmation — you get it when you check in.' },
    ],
  },
  {
    id: 'payments', title: 'Payments & credit', icon: 'card', blurb: 'Cards, promo codes, credit, receipts',
    articles: [
      { slug: 'pay', q: 'How do I pay?', tags: 'payment card checkout apple pay google pay saved card',
        steps: [
          'On CONFIRM & PAY leave PAY NOW selected.',
          'Choose a saved card under YOUR CARDS, or Use a different card and enter it.',
          'Tap CONFIRM & PAY.',
        ],
        notes: ['A new card is saved on file for any overages.', 'Apple Pay and Google Pay show up once you have a card saved.'] },
      { slug: 'someone-else-pays', q: 'Can someone else pay for my booking?', tags: 'someone else pays client pays payment link',
        steps: [
          'On CONFIRM & PAY tap SOMEONE ELSE PAYS.',
          'Enter their name (optional) and phone or email, then tap SEND PAYMENT LINK.',
          'You’ll see WAITING ON … with a countdown, and you’re texted when they pay.',
        ],
        notes: ['The time is held for 30 minutes. If they don’t pay in time, the slot reopens.', 'You need a saved card on your account first.'] },
      { slug: 'promo', q: 'How do I use a promo code?', tags: 'promo discount code coupon',
        steps: ['On CONFIRM & PAY enter the code in Promo code and tap APPLY.', 'The discount shows in the summary. REMOVE takes it off.'] },
      { slug: 'credit', q: 'What is studio credit and how do I use it?', tags: 'studio credit balance use save for later', popular: true,
        a: 'Made Kulture gives studio credit instead of refunds. Credit never expires and is applied automatically at checkout as a STUDIO CREDIT line.',
        steps: ['See your balance on your Dashboard (Studio credit tile).', 'At checkout, tap × next to the credit to save it for later, or Use it to put it back.'],
        notes: ['There’s no itemized credit history in the account yet — contact support if you need one.'] },
      { slug: 'refunds', q: 'Do you give refunds?', tags: 'refund money back',
        a: 'Bookings come back as studio credit rather than a card refund. Credit never expires and applies automatically to your next booking. See [the cancellation policy](?a=cancel-policy).' },
      { slug: 'cards', q: 'How do I add or remove a saved card?', tags: 'card payment method saved add remove',
        steps: [SETTINGS, 'Choose Payment methods.', 'Tap + ADD CARD, enter the card and tap SAVE CARD — or tap REMOVE next to a card and confirm.'],
        notes: ['A card used for an upcoming booking, or one that ended in the last 7 days, can’t be removed yet.'] },
      { slug: 'receipt', q: 'Where’s my receipt?', tags: 'receipt invoice itemized',
        a: 'Your confirmation email has a View your card receipt link. Need an itemized receipt or invoice? Contact support with your booking date.' },
      { slug: 'add-gear-later', q: 'What is “+ ADD GEAR” on my booking?', tags: 'add gear payment pending equipment later',
        a: 'If you left checkout with gear still in your kit, it stays saved and My Bookings offers + ADD GEAR on your upcoming booking. Tapping it opens a separate payment for that gear, which shows “payment pending” until it’s paid.' },
    ],
  },
  {
    id: 'arrival', title: 'Arriving & your session', icon: 'key', blurb: 'Check-in, door codes, adding time',
    articles: [
      { slug: 'door-code', q: 'How do I check in and get my door code?', tags: 'check in door code arrive pin front back door', popular: true,
        steps: [
          'When you arrive, open the check-in link from your confirmation text or email — or tap CHECK IN · DOOR CODE in My Bookings.',
          'Confirm the guests in your party.',
          'Tap CHECK IN — SHOW MY CODE. Your FRONT DOOR (and BACK DOOR, if included) codes appear.',
          'Type the code on the keypad, then press the UNLOCK button.',
          'When you leave, tap CHECK OUT — I’M LEAVING.',
        ],
        notes: ['Your code is not in the confirmation — only on the check-in page.', 'Check-in opens 30 minutes before your start, but codes only work from your start time.', 'No signal at the door? Reply CODE to your confirmation text and it’s texted back.', 'Lost the link? Go to [Check in](/checkin) and enter your phone number to have it texted to you.'] },
      { slug: 'code-not-working', q: 'My door code isn’t working', tags: 'code not working locked out keypad unlock', popular: true,
        a: 'Almost every time, it’s the unlock button: type the code, THEN press UNLOCK. The code alone does nothing.',
        notes: ['Codes only work during your booked time — not before your start.', 'Extended or rescheduled? You got a new code. Reopen your check-in link for the current one.', 'The front and back doors have different codes.'] },
      { slug: 'early', q: 'Can I arrive early?', tags: 'early setup arrive',
        a: 'Your set unlocks at your booked start time, so you can’t get in early. Arrive a few minutes ahead and be ready to start on time — setup and breakdown happen inside your booked time.' },
      { slug: 'add-time', q: 'How do I add time during my session?', tags: 'add time extend extension stay longer',
        steps: [
          'On your set’s tablet tap ADD TIME.',
          'Pick a length (e.g. + 30 MIN, + 1 HOUR).',
          'Enter the last 4 digits of the booking’s phone number and tap CONFIRM & CHARGE.',
        ],
        notes: ['ADD TIME appears once your session has started and the set is free after you.', 'No card on file? You’re texted a link to pay on your phone.', 'Your door code keeps working until the new end time.'] },
      { slug: 'overtime', q: 'What if I go over my time?', tags: 'overtime late over time',
        a: 'Going more than 15 minutes past your booked time is charged as an additional hour.' },
      { slug: 'help-at-studio', q: 'How do I get help while I’m at the studio?', tags: 'help tablet team staff june kiosk',
        steps: ['On the set tablet, tap ASK JUNE for quick questions — sets, gear, rules, directions.', 'Need a person? Tap GET THE TEAM, then RING THE TEAM. The screen updates when someone is on the way.'] },
      { slug: 'leaving', q: 'What do I need to do before I leave?', tags: 'clean up leave props checkout',
        a: 'Put every prop back where you found it, leave the set clean, and finish breakdown before your time ends. A cleaning fee (minimum $150) may apply if the set isn’t left as you found it.' },
      { slug: 'parking', q: 'Where do I park?', tags: 'parking car truck ramp',
        a: 'There’s limited parking out front and street parking at the rear. Only higher vehicles (SUVs, trucks, vans without tow hitches) should use the steep ramp to Studio One.' },
      { slug: 'climate', q: 'Is the studio air-conditioned?', tags: 'ac air conditioning heat cold temperature',
        a: 'There’s no central A/C — we use large fans for cooling and a heater for warmth, and partial A/C has been added as part of ongoing upgrades. Dress for the weather.' },
    ],
  },
  {
    id: 'changes', title: 'Changes & cancellations', icon: 'swap', blurb: 'Reschedule, cancel, credit back',
    articles: [
      { slug: 'my-bookings', q: 'Where do I see my bookings?', tags: 'my bookings upcoming past',
        a: 'Members: open My Bookings (on phones, More → My Bookings). Bookings are split into UPCOMING and PAST & CANCELLED, with RESCHEDULE, CANCEL, CHECK IN · DOOR CODE and + CALENDAR on upcoming ones. Guests: use the View or change my booking link in your confirmation email.' },
      { slug: 'reschedule', q: 'How do I reschedule?', tags: 'reschedule move change time date', popular: true,
        steps: [
          'Members: in My Bookings tap RESCHEDULE. Guests: open View or change my booking from your email and tap Change my time.',
          'Pick a NEW DATE and NEW START TIME.',
          'Tap CONFIRM NEW TIME.',
        ],
        notes: ['Same set, same length, same price — only the time changes.', 'Online changes need 48+ hours’ notice. Plus members signed in to their account can change later.', 'Moving a booking issues a new door code; the old one stops working.', 'Full Studio Takeovers can’t be moved online — contact support.'] },
      { slug: 'cancel', q: 'How do I cancel?', tags: 'cancel booking',
        steps: ['Sign in and open My Bookings.', 'Tap CANCEL on the booking and confirm.', 'You’ll see the amount added to your account as studio credit.'],
        notes: ['CANCEL appears 48+ hours before your start — or any time before the start for Plus members.', 'Booked as a guest? Contact support to cancel.', 'Once a session has started it can’t be cancelled online.'] },
      { slug: 'cancel-policy', q: 'What’s the cancellation policy?', tags: 'cancellation policy 48 hours late fee credit',
        a: 'Cancel 48 or more hours before your start and the full booking value comes back as studio credit. Cancellations within 48 hours aren’t credited — unless you’re a Plus member, who is credited in full any time before the session starts. Full warehouse bookings cancelled within 48 hours carry a 25% late fee for everyone (Plus included); the other 75% comes back as credit.' },
      { slug: 'save-with-plus', q: 'What is SAVE WITH PLUS on my booking?', tags: 'save with plus inside 48 late change',
        a: 'Inside 48 hours, individual-set bookings show SAVE WITH PLUS. Joining Plus unlocks RESCHEDULE and CANCEL on that booking. Booked as a guest? Tap Create account & save it on your manage page, using the same email you booked with.' },
      { slug: 'flexibility', q: 'What does “Booking flexibility” mean?', tags: 'booking flexibility heads up needs approval late changes',
        a: 'It’s on your Dashboard and tracks last-minute changes. Flexible means you can cancel or move freely; Heads-up means you’ve made recent last-minute changes; Needs approval means changes inside 48 hours need a quick OK from the studio. Late changes clear after 30 days, or sooner when you use your next booking as planned.' },
    ],
  },
  {
    id: 'rules', title: 'Studio rules', icon: 'shield', blurb: 'What’s allowed in the studio',
    articles: [
      { slug: 'messy', q: 'Can I use paint, glitter, fake blood or smoke bombs?', tags: 'messy paint glitter blood smoke oil powder confetti',
        a: 'No. Paint, fake blood, glitter, smoke bombs and excessive oils aren’t allowed. Anything messy or outside normal studio use needs written approval from the studio before the shoot — the answer is no unless it’s been approved in writing.' },
      { slug: 'water', q: 'What are the rules for the water sets?', tags: 'pool tank water fish',
        a: 'Nothing goes in or near the water that could contaminate it — no paint, dyes, oils or similar, with no exceptions, because contaminants stain the set and ruin the filtration. Get color with gels, lighting and wardrobe instead. Each water set is its own set and can’t be moved or combined.' },
      { slug: 'fog', q: 'Can I use fog or haze?', tags: 'fog haze machine',
        a: 'Only with a Full Studio Takeover, or when your party is the only booking in the building.' },
      { slug: 'audio', q: 'Can I record audio?', tags: 'audio sound video interview podcast noise',
        a: 'The studio isn’t soundproofed and sits near the I-45 freeway. For audio, we recommend a Full Studio Takeover.' },
      { slug: 'nudity', q: 'Is nudity allowed?', tags: 'nude implied boudoir',
        a: 'Not during shared bookings unless your party is the only booking in the building. A Full Studio Takeover is recommended.' },
      { slug: 'kids', q: 'Can I bring kids?', tags: 'children kids baby family',
        a: 'Yes — children count toward your guest limit. Keep in mind it’s a shared working space.' },
      { slug: 'standing', q: 'What is account standing?', tags: 'account standing warning probation suspended incident points',
        a: 'Every account starts in good standing. If a booking leads to an incident (props not put back, a messy set, too many guests, unbooked sets or gear, unpaid overtime, damage, rules or conduct), it may be recorded with points that drop off after 12 months. Levels: Good standing, Warning (rewards and short-notice booking paused), Probation (also pauses Plus cancellation protection; bookings may need approval) and Suspended (can’t book). Your Dashboard shows your standing, and you’re emailed when an incident is recorded. Questions about an incident? Contact support.' },
      { slug: 'all-rules', q: 'Where can I read all the rules?', tags: 'rules terms policy waiver',
        a: 'See [Studio Rules](/studio-rules) and [Terms & Conditions](/terms).' },
    ],
  },
  {
    id: 'profile', title: 'Your profile & portfolio', icon: 'user', blurb: 'Photos, bio, roles, credits',
    articles: [
      { slug: 'edit-profile', q: 'How do I edit my profile?', tags: 'edit profile name bio account type phone instagram',
        steps: [
          SETTINGS + ' It opens on Edit profile.',
          'Change your ACCOUNT TYPE (Customer, Creative, Vendor or Brand), FULL NAME, PHONE, INSTAGRAM, BIO (up to 600 characters) or LINKS.',
          'Tap SAVE CHANGES.',
        ],
        notes: ['Customer accounts see only the basics. Switch to Creative, Vendor or Brand to unlock the directory fields.', 'Your email is changed in Login & security, not here.'] },
      { slug: 'profile-photo', q: 'How do I change my profile photo?', tags: 'avatar profile picture logo headshot',
        steps: [SETTINGS, 'In Edit profile, under PROFILE PHOTO (LOGO for brands), tap UPLOAD PHOTO or CHANGE PHOTO.', 'Tap SAVE CHANGES — the photo isn’t kept until you do.'],
        notes: ['Up to 25 MB. Location data is removed automatically.'] },
      { slug: 'portfolio-add', q: 'How do I add photos to my portfolio?', tags: 'portfolio photos upload images gallery work crop', popular: true,
        steps: [
          SETTINGS,
          'Choose Portfolio.',
          'The first time, tick the box confirming you own the images and everyone shown is 18+ and consented.',
          'Tap + Add photos (or drag files onto the grid on a computer).',
          'With one photo, frame it in the crop window and tap Save photo. Several at once are centre-cropped automatically.',
        ],
        notes: ['Up to 12 photos (15 for First 100 members). Each up to 60 MB.', 'Photos are cropped to a 4:5 portrait and save as soon as they upload — no Save button needed.'] },
      { slug: 'portfolio-manage', q: 'How do I reorder, re-crop or delete portfolio photos?', tags: 'reorder rearrange delete remove recrop portfolio',
        steps: [
          SETTINGS + ' Then choose Portfolio.',
          'On a computer, hover a photo to see its buttons (always visible on phones).',
          'Tap ⟳ to re-crop, ✕ to delete, or drag the ⠿ handle to reorder.',
        ],
        notes: ['Changes save straight away. Deleting has no confirmation and can’t be undone.', 'Your first photo is the one people see first.'] },
      { slug: 'portfolio-18', q: 'How do I mark a photo as 18+?', tags: 'mature 18+ nsfw sensitive blur',
        steps: [SETTINGS + ' Then choose Portfolio.', 'Tap 18+ on the photo. Tap again to remove it.'],
        notes: ['18+ photos are covered on your profile until a viewer taps Reveal, and never appear in Explore.'] },
      { slug: 'photo-credits', q: 'How do I tag or credit people in a photo?', tags: 'tag credit collaborator model mua photographer',
        steps: [
          SETTINGS + ' Then choose Portfolio.',
          'Tap @ TAG on the photo.',
          'Under ADD A CREDIT, pick their role on the shoot first.',
          'Search the directory by name or @instagram and tap them — or tap “Not on the directory? Credit them anyway” and add their name or @instagram.',
        ],
        notes: ['Tagged members see the photo on their TAGGED tab.', 'Remove a credit with the ✕ next to it.'] },
      { slug: 'untag', q: 'How do I remove myself from a photo I’m tagged in?', tags: 'untag remove tag tagged',
        steps: ['Tap Profile and open the TAGGED tab.', 'Tap the photo, then the person icon in its corner.', 'Tap Remove me and confirm.'],
        notes: ['The photo stays in the other member’s portfolio; it just leaves your TAGGED tab.'] },
      { slug: 'roles', q: 'How do I change my roles?', tags: 'roles what you do job photographer model',
        steps: [SETTINGS, 'In Edit profile under WHAT YOU DO, tap a role to remove it, then search and tap new ones.', 'Tap SAVE CHANGES.'],
        notes: ['Up to 3 roles, picked from the studio’s list. Brands don’t have roles.'] },
      { slug: 'links-reel', q: 'How do I add links, Instagram or a video reel?', tags: 'links website instagram reel video youtube vimeo',
        steps: [
          SETTINGS,
          'In Edit profile fill in INSTAGRAM, and under LINKS tap + Add link (a label and the URL).',
          'For a reel, go to Credits & CV and paste a YouTube or Vimeo link into VIDEO / REEL LINK.',
          'Tap SAVE CHANGES.',
        ],
        notes: ['Up to 8 links.'] },
      { slug: 'credits-cv', q: 'How do I add credits or upload my CV?', tags: 'credits resume cv publications campaigns awards pdf',
        steps: [SETTINGS + ' Then choose Credits & CV.', 'Tap + Add credit and fill in the type, Year, Title / client and Your role.', 'To add a CV, tap UPLOAD CV (PDF).', 'Tap SAVE CHANGES.'],
        notes: ['Up to 40 credits. The CV must be a PDF under 10 MB and isn’t kept until you tap SAVE CHANGES.'] },
      { slug: 'banner', q: 'How do I change my banner color or add a cover photo?', tags: 'banner color cover photo header first 100',
        steps: [SETTINGS + ' Then choose Banner & cover.', 'Pick a BANNER COLOR. First 100 members can also tap ADD COVER PHOTO.', 'Tap SAVE CHANGES.'] },
    ],
  },
  {
    id: 'directory', title: 'Directory & messages', icon: 'search', blurb: 'Getting listed, finding people, messaging',
    articles: [
      { slug: 'get-listed', q: 'How do I get listed in the creative directory?', tags: 'join directory listed visible opt in not showing', popular: true,
        steps: [
          SETTINGS,
          'In Edit profile set ACCOUNT TYPE to Creative, Vendor or Brand.',
          'Add your name, at least one role (brands skip this), and a BIO.',
          'Add at least one of: a portfolio photo, a link, or your Instagram. Tap SAVE CHANGES.',
          'Go to Directory & notifications, tick “List me in the creative directory”, and tap SAVE CHANGES.',
        ],
        notes: ['Edit profile shows a checklist of what’s left, and “You’re listed in the creative directory” once you’re live.', 'Production Services vendors also need to sign the Vendor Agreement in Service listings.', 'The directory is members-only both ways: you need to be listed to browse, message, follow or use castings.'] },
      { slug: 'cant-see-directory', q: 'Why can’t I see anyone in the directory?', tags: 'directory empty locked cant browse listing off finish profile',
        a: 'The directory is only open to members who are listed in it. If you see “Your listing is off” or “Almost there — finish your profile”, follow [How do I get listed](?a=get-listed) — the card shows exactly what’s missing.' },
      { slug: 'find-people', q: 'How do I find people?', tags: 'search browse explore people filter role collaborator',
        steps: [
          'Tap Directory and use the tabs: Home, Explore, People, Services, Castings, Messages.',
          'On Explore, search by name or @handle, or tap Filter by role.',
          'Tap someone to open their profile.',
        ],
        notes: ['Members without portfolio photos only show under People, not Explore.'] },
      { slug: 'message', q: 'How do I message another member?', tags: 'message dm chat inbox send',
        steps: ['Open their profile and tap Message.', 'Type your message and tap Send.', 'All your chats are under Messages.'],
        notes: ['Messages are text only (up to 2,000 characters).', 'Both of you need to be listed in the directory.', 'Unread chats show a badge on Messages.'] },
      { slug: 'follow', q: 'How do I follow someone?', tags: 'follow unfollow followers following',
        steps: ['Open their profile and tap Follow (tap Following to unfollow).', 'Tap the follower or following count on any profile to see the list.'] },
      { slug: 'privacy-contact', q: 'How do I show or hide my email and phone?', tags: 'privacy email phone hide unlist leave directory',
        steps: [SETTINGS + ' Then choose Directory & notifications.', 'Tick or untick “Show my email to other members” and “Show my phone to other members”.', 'Tap SAVE CHANGES.'],
        notes: ['Both are off by default and only ever shown to signed-in members.', 'Unticking “List me in the creative directory” takes you out of the directory — and you lose browsing and messaging too.'] },
      { slug: 'message-alerts', q: 'How do I get texts or emails about new messages?', tags: 'message notifications email text alerts',
        steps: [SETTINGS + ' Then choose Directory & notifications.', 'Tick “Email me about new messages and casting interest” and/or “Text me about new messages and casting interest”.', 'Tap SAVE CHANGES.'] },
      { slug: 'report', q: 'How do I report a photo or listing?', tags: 'report flag inappropriate abuse spam',
        steps: [
          'Photo: open it on the member’s profile, tap ⋯, then Report. Pick a reason and tap Send report.',
          'Listing: open it and tap Report this listing. Pick a reason and tap SEND REPORT.',
        ],
        notes: ['Reports are anonymous. The studio reviews every one.', 'Problem with a person or a message? Contact support with their name.'] },
    ],
  },
  {
    id: 'services', title: 'Service listings', icon: 'tag', blurb: 'For vendors offering rentals and services',
    articles: [
      { slug: 'add-listing', q: 'How do I add a service listing?', tags: 'add listing service vendor production services rental create', popular: true,
        a: 'Service listings are how vendors offer rentals and services (vehicles, wardrobe, props, equipment, animals, catering) to other members.',
        steps: [
          SETTINGS,
          'In Edit profile, set ACCOUNT TYPE to Vendor (or add a Production Services role) and tap SAVE CHANGES.',
          'Choose Service listings.',
          'First time only: read the Vendor Agreement, tick the box, type your full name and tap I AGREE.',
          'Tap + ADD LISTING.',
          'Pick a CATEGORY and enter a TITLE (e.g. “2021 Mercedes G-Wagon (black)”).',
          'Under PRICE enter an amount and choose Per hour, Per half day, Per day, Flat rate, Per project — or Ask for a quote.',
          'Fill in DETAILS (what it is, condition, what’s included) and any NOTES (delivery, deposit, driver).',
          'Add SEARCH TAGS — type a tag and press Enter (up to 8).',
          'Tap + PHOTO to add up to 6 photos.',
          'Tap SAVE LISTING.',
        ],
        notes: [
          'Your listing goes live right away — no approval step.',
          'It only shows to others once your own profile is listed in the directory (name, role, bio, a photo/link/Instagram, opted in, and the signed Vendor Agreement). See [How do I get listed](?a=get-listed).',
          'Up to 12 listings. Tick “Starting price” to show the price as “From $…”.',
          'Payment is arranged directly between you and the member — Made Kulture doesn’t take payment for listings.',
        ] },
      { slug: 'edit-listing', q: 'How do I edit a listing?', tags: 'edit listing change price photos tags',
        steps: [SETTINGS + ' Then choose Service listings.', 'Tap EDIT on the listing, make your changes, and tap SAVE LISTING.'],
        notes: ['Photos you remove are deleted when you save.'] },
      { slug: 'hide-listing', q: 'How do I hide or delete a listing?', tags: 'pause hide unpublish delete remove listing',
        steps: [SETTINGS + ' Then choose Service listings.', 'Tap HIDE to take it down (SHOW brings it back) — or DELETE to remove it for good.'],
        notes: ['Hidden listings still count toward the 12-listing limit.', 'Deleting also deletes the listing’s photos.'] },
      { slug: 'under-review', q: 'Why does my listing say UNDER REVIEW?', tags: 'under review hold reported hidden',
        a: 'A listing is pulled from view while the studio reviews it — after several member reports, or when the studio holds it. HIDE/SHOW won’t bring it back. Contact support if you think it’s a mistake.' },
      { slug: 'listing-requests', q: 'How do I receive and answer requests? (vendors)', tags: 'vendor requests respond messages notifications',
        a: 'Each request arrives as a message in Messages, starting with “REQUEST:” and the date needed. Reply there to agree on dates, price and payment. You’re notified by email and app notification, and by text if you opted in (Settings → Directory & notifications).',
        notes: ['There’s no accept/decline button — everything happens in the message thread.'] },
      { slug: 'browse-services', q: 'How do I find and request a service?', tags: 'services tab search request rent car props wardrobe',
        steps: [
          'Open Directory and choose the Services tab.',
          'Search (try car, gown, pole…) or tap a category.',
          'Tap a listing, then REQUEST.',
          'Pick the DATE NEEDED, add DETAILS (times, location, delivery), and tap SEND REQUEST.',
        ],
        notes: ['The request opens a message thread with the vendor. Price, payment and logistics are arranged directly with them.'] },
    ],
  },
  {
    id: 'castings', title: 'Castings', icon: 'cast', blurb: 'Post a casting, apply, build your team',
    articles: [
      { slug: 'post-casting', q: 'How do I post a casting?', tags: 'post casting create call model mua crew tfp paid', popular: true,
        steps: [
          'Tap Castings, then + Post a casting.',
          'Enter a TITLE and DESCRIPTION.',
          'Choose COMPENSATION: Paid, Unpaid or TFP (trade). Tick 18+ if it’s mature.',
          'Pick the ROLES YOU NEED (up to 8).',
          'Optional: add a STUDIO PLAN (a set or full buyout), EQUIPMENT, and a DATE & START.',
          'Tap POST CASTING.',
          'Optional: on the casting’s page, add up to 6 MOOD BOARD images.',
        ],
        notes: ['Up to 3 active castings at once. Castings expire after 30 days.', 'Posting doesn’t book the studio — use Book this → on the casting when you’re ready.'] },
      { slug: 'manage-casting', q: 'How do I edit, close or renew my casting?', tags: 'edit close reopen renew expired delete casting',
        steps: ['Tap Castings, then My castings, and open the casting.', 'Use Edit, Close casting / Reopen, Renew (30 days) (on expired castings) or Delete.'] },
      { slug: 'apply-casting', q: 'How do I apply to a casting?', tags: 'apply casting interested respond',
        steps: ['Tap Castings and filter by All, Paid, Unpaid or TFP, or search.', 'Open a casting and tap I’m interested.', 'A message thread with the organizer opens.'],
        notes: ['You need to be listed in the directory to apply.'] },
      { slug: 'applicants', q: 'How do I review applicants and pick my team?', tags: 'applicants approve confirm team remove',
        steps: [
          'Open your casting — APPLICANTS is at the top (new ones are marked NEW).',
          'Choose a Role… for a person and tap Approve — or ✕ to remove them.',
          'Approved people move to THE TEAM and get a TEAM CHANNEL chat for the shoot.',
        ],
        notes: ['Approving notifies the person. Removing doesn’t.', 'The number on the Castings icon counts new applicants you haven’t looked at.'] },
      { slug: 'invite-casting', q: 'How do I invite someone to my casting?', tags: 'invite member casting',
        steps: ['Open their profile in the Directory.', 'Tap Invite ▾ and choose one of your open castings.'] },
    ],
  },
  {
    id: 'plus', title: 'Made Kulture Plus', icon: 'star', blurb: 'Membership, perks and renewal',
    articles: [
      { slug: 'what-is-plus', q: 'What is Made Kulture Plus?', tags: 'plus membership perks benefits', popular: true,
        a: 'Plus is our paid yearly membership. On top of a free account it adds short-notice booking inside the 48-hour window, cancellation protection (full credit any time before an individual-set session starts), and no-show credit on request. It doesn’t change the hourly rate. [Learn more](/plus)' },
      { slug: 'join-plus', q: 'How do I join Plus?', tags: 'join plus upgrade subscribe',
        steps: ['Tap the Go Plus card on your Dashboard (or Settings → Membership).', 'Enter your card and tap GO PLUS.', 'You’ll see “✓ You’re a Plus member”.'],
        notes: ['The intro price is for first-time members only. Plus renews yearly on your saved card.'] },
      { slug: 'plus-autorenew', q: 'How do I turn off Plus auto-renew?', tags: 'cancel plus auto renew stop renewal',
        steps: ['Open your Dashboard.', 'On your Plus card, tap Turn off auto-renew (Turn on auto-renew switches it back).'],
        notes: ['Your benefits continue to the end of the paid term and you won’t be charged again.', 'Membership fees aren’t refundable.'] },
    ],
  },
  {
    id: 'account', title: 'Account & privacy', icon: 'lock', blurb: 'Email, password, deleting your account',
    articles: [
      { slug: 'change-password', q: 'How do I change my password?', tags: 'change password security',
        steps: [SETTINGS + ' Then choose Login & security.', 'Fill in CURRENT PASSWORD, NEW PASSWORD and CONFIRM NEW PASSWORD.', 'Tap UPDATE PASSWORD.'],
        notes: ['Signed up with Google or Apple? There’s no password to change — keep using that button.'] },
      { slug: 'change-email', q: 'How do I change my email?', tags: 'change email address login',
        steps: [SETTINGS + ' Then choose Login & security.', 'Under Change email enter your NEW EMAIL and tap UPDATE EMAIL.', 'Click the confirmation link sent to the new address.'],
        notes: ['Nothing changes until you click that link. Your bookings, cards and Plus move to the new email.'] },
      { slug: 'sms-reminders', q: 'How do I turn booking text reminders on or off?', tags: 'sms text reminders stop texts',
        steps: [SETTINGS + ' Then choose Directory & notifications.', 'Tick or untick “Send me SMS reminders before my bookings”.', 'Tap SAVE CHANGES.'],
        notes: ['You can also reply STOP to any text.'] },
      { slug: 'delete-account', q: 'How do I delete my account?', tags: 'delete account remove data privacy close',
        steps: [
          SETTINGS + ' Then choose Login & security.',
          'Scroll to Delete account and tap DELETE MY ACCOUNT.',
          'Type DELETE and tap PERMANENTLY DELETE.',
        ],
        notes: [
          'This permanently deletes your login, profile, directory listing, portfolio, messages, saved cards and any studio credit. Plus stops renewing and isn’t refunded.',
          'Past booking records are kept for our business records, as described in our [Privacy Policy](/privacy-policy).',
          'You’ll need to cancel or finish any upcoming bookings first. Can’t sign in? Contact support and we’ll delete it for you.',
        ] },
      { slug: 'privacy', q: 'How is my information used?', tags: 'privacy data policy',
        a: 'We use your information to run your bookings and account, never for advertising, and we don’t track you across other apps or websites. Read the full [Privacy Policy](/privacy-policy).' },
    ],
  },
  {
    id: 'visit', title: 'Tours', icon: 'pin', blurb: 'See the studio before you book',
    articles: [
      { slug: 'tour', q: 'Can I tour the studio first?', tags: 'tour visit see walk through',
        steps: [
          'Go to [Book a tour](/tour).',
          'Choose Available times or Request a custom time, then pick a date and time.',
          'Enter your name and phone and tap REQUEST TOUR. We confirm by text.',
        ],
        notes: ['Tours are free and take about 30 minutes.', 'Can’t make it? Use the cancel link in your confirmation.'] },
    ],
  },
]

export const ALL_ARTICLES = CATEGORIES.flatMap(c => c.articles.map(a => ({ ...a, categoryId: c.id, categoryTitle: c.title })))
